from typing import TYPE_CHECKING, List, Union, Dict, Optional, Any

# Import actual types for runtime
from ._types import Project, State, Label, Link, Issue, IssueActivity, IssueComment, Module
from .api import PlaneClient as _BaseClient

# Create unified type exports
PlaneType = Union[Project, State, Label, Link, Issue, IssueActivity, IssueComment, Module]

class PlaneClient(_BaseClient):
    """
    Main client class with type hints for better IDE support
    """
    if TYPE_CHECKING:
        # Project methods
        async def get_projects(self) -> List[Project]: ...
        async def get_project_details(self, project_id: str) -> Project: ...
        async def create_project(self, name: str, identifier: str, **kwargs) -> Project: ...
        async def update_project(self, project_id: str, **kwargs) -> Project: ...
        async def delete_project(self, project_id: str) -> bool: ...
        
        # State methods
        async def get_states(self, project_id: str) -> List[State]: ...
        async def get_state_details(self, project_id: str, state_id: str) -> State: ...
        async def create_state(self, name: str, color: str, project_id: str, **kwargs) -> State: ...
        async def update_state(self, project_id: str, state_id: str, **kwargs) -> State: ...
        async def delete_state(self, project_id: str, state_id: str) -> bool: ...

        # Label methods
        async def get_labels(self, project_id: str) -> List[Label]: ...
        async def get_label_details(self, project_id: str, label_id: str) -> Label: ...
        async def create_label(self, name: str, project_id: str, **kwargs) -> Label: ...
        async def update_label(self, name: str, project_id: str, label_id: str, **kwargs) -> Label: ...
        async def delete_label(self, project_id: str, label_id: str) -> bool: ...

        # Link methods
        async def get_links(self, project_id: str, issue_id: str) -> List[Link]: ...
        async def get_link_details(self, project_id: str, issue_id: str, link_id: str) -> Link: ...
        async def create_link(self, url: str, project_id: str, issue_id: str, **kwargs) -> Link: ...
        async def update_link(self, project_id: str, issue_id: str, link_id: str, **kwargs) -> Link: ...
        async def delete_link(self, project_id: str, issue_id: str, link_id: str) -> bool: ...

        # Issue methods
        async def get_issues(self, project_id: str) -> List[Issue]: ...
        async def get_issue_details(self, project_id: str, issue_id: str) -> Issue: ...
        async def create_issue(self, name: str, project_id: str, **kwargs) -> Issue: ...
        async def update_issue(self, name: str, project_id: str, issue_id: str, **kwargs) -> Issue: ...
        async def delete_issue(self, project_id: str, issue_id: str) -> bool: ...

        # IssueActivity methods
        async def get_issue_activity(self, project_id: str, issue_id: str) -> List[IssueActivity]: ...
        async def get_activity_details(self, project_id: str, issue_id: str, activity_id: str) -> IssueActivity: ...

        # IssueComment methods
        async def get_issue_comments(self, project_id: str, issue_id: str) -> List[IssueComment]: ...
        async def get_comment_details(self, project_id: str, issue_id: str, comment_id: str) -> IssueComment: ...
        async def create_comment(self, url: str, project_id: str, issue_id: str, **kwargs) -> IssueComment: ...
        async def update_comment(self, project_id: str, issue_id: str, comment_id: str, **kwargs) -> IssueComment: ...
        async def delete_comment(self, project_id: str, issue_id: str, comment_id: str) -> bool: ...

        # Module methods
        async def get_modules(self, project_id: str) -> List[Module]: ...
        async def get_module_details(self, project_id: str, module_id: str) -> Module: ...
        async def create_module(self, name: str, project_id: str, **kwargs) -> Module: ...
        async def update_module(self, name: str, project_id: str, module_id: str, **kwargs) -> Module: ...
        async def delete_module(self, project_id: str, module_id: str) -> bool: ...
        
        # Internal method
        async def _request(self, method: str, endpoint: str, **kwargs) -> Optional[Dict[str, Any]]: ...

# Export everything needed
__all__ = [
    "PlaneClient",
    "Project",
    "State",
    "Label",
    "Link",
    "Issue",
    "IssueActivity",
    "IssueComment",
    "Module",
    "PlaneType"
]